package test.shiro.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.id
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.name
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.phone
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.age
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.address
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.sex
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.status
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.salt
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.update_time
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.update_by
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.create_time
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.create_by
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.delete_flag
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    private Integer deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.id
     *
     * @return the value of auth_user.id
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.id
     *
     * @param id the value for auth_user.id
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.name
     *
     * @return the value of auth_user.name
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.name
     *
     * @param name the value for auth_user.name
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.phone
     *
     * @return the value of auth_user.phone
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.phone
     *
     * @param phone the value for auth_user.phone
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.age
     *
     * @return the value of auth_user.age
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.age
     *
     * @param age the value for auth_user.age
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.address
     *
     * @return the value of auth_user.address
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.address
     *
     * @param address the value for auth_user.address
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.sex
     *
     * @return the value of auth_user.sex
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.sex
     *
     * @param sex the value for auth_user.sex
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.status
     *
     * @return the value of auth_user.status
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.status
     *
     * @param status the value for auth_user.status
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.salt
     *
     * @return the value of auth_user.salt
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.salt
     *
     * @param salt the value for auth_user.salt
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.update_time
     *
     * @return the value of auth_user.update_time
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.update_time
     *
     * @param updateTime the value for auth_user.update_time
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.update_by
     *
     * @return the value of auth_user.update_by
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.update_by
     *
     * @param updateBy the value for auth_user.update_by
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.create_time
     *
     * @return the value of auth_user.create_time
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.create_time
     *
     * @param createTime the value for auth_user.create_time
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.create_by
     *
     * @return the value of auth_user.create_by
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.create_by
     *
     * @param createBy the value for auth_user.create_by
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.delete_flag
     *
     * @return the value of auth_user.delete_flag
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.delete_flag
     *
     * @param deleteFlag the value for auth_user.delete_flag
     *
     * @mbg.generated Wed Aug 22 11:28:31 CST 2018
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}